apiVersion: apps/v1
kind: Deployment
metadata:
  name: d1-gaming-event-backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: d1-gaming-event-backend
  template:
    metadata:
      labels:
        app: d1-gaming-event-backend
        version: 1.1.4
    spec:
      volumes: 
        - name: google-cloud-key
          secret: 
            secretName: pubsub-key
      containers:
        - name: d1-gaming-event-backend-container
          image: gcr.io/d1gamingapp/d1-gaming-event-backend:v1.1.4
          volumeMounts: 
            - name: google-cloud-key
              mountPath: /var/secrets/google
          env: 
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json 
          resources:
            limits:
              cpu: 0.2
              memory: 1Gi
            requests:
              cpu: 0.2
              memory: 1Gi
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          readinessProbe:
              httpGet:
                path: /ping
                port: 8081
              periodSeconds: 30
              timeoutSeconds: 1
              successThreshold: 1
              failureThreshold: 5
                    
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "d1-gaming-event-backend-service"
spec:
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8081
  selector:
    app: "d1-gaming-event-backend"
  type: "LoadBalancer"